# Generated by Django 3.0.7 on 2020-06-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=45)),
                ('direccion_bodega', models.CharField(max_length=45)),
                ('estado_bodega', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'bodegas',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'productos'},
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_orden', models.IntegerField()),
                ('fecha_orden', models.DateTimeField()),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.Bodega')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.Producto')),
            ],
        ),
    ]
