# Generated by Django 3.0.7 on 2020-06-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_auto_20200621_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'ordenes'},
        ),
        migrations.AlterField(
            model_name='bodega',
            name='estado_bodega',
            field=models.IntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto'), (2, 'Especial')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.IntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto'), (2, 'Especial')], default=1),
        ),
    ]
