# Generated by Django 3.0.7 on 2020-06-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20200622_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado_bodega',
            field=models.CharField(choices=[('0', 'Cerrado'), ('1', 'Abierto'), ('2', 'Especial')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(choices=[('0', 'Cerrado'), ('1', 'Abierto'), ('2', 'Especial')], default='1', max_length=1),
        ),
    ]
