# Generated by Django 3.0.7 on 2020-06-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_auto_20200622_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle_producto',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Bodega'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.Producto'),
        ),
    ]
